# -*- coding: utf-8 -*-
"""lvadsusr159_b_kartik_lab3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NUI_T3Z6gESuuqu5YILTQ2a2f5ZrsoIx
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
import warnings
warnings.filterwarnings("ignore")

df=pd.read_csv('/content/customer_segmentation.csv')

df

df.info()

df.isnull().sum()

df.bfill(inplace=True)

from matplotlib import pyplot as plt
df.plot(kind='scatter', x='Recency', y='Income', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

df=df.drop(['Education','Marital_Status','Dt_Customer'],axis=1)

import numpy as nm
import matplotlib.pyplot as mtp
import pandas as pd
from sklearn.cluster import KMeans
x = df.values

wcss_list= []
for i in range(1, 11):
    kmeans = KMeans(n_clusters=i, init='k-means++', random_state= 42)
    kmeans.fit(x)
    wcss_list.append(kmeans.inertia_)

mtp.plot(range(1, 11), wcss_list)
mtp.title('The Elbow Method Graph')
mtp.xlabel('Number of clusters(k)')
mtp.ylabel('wcss_list')
mtp.show()

"""# Optimal number of clusters - 3"""

kmeans = KMeans(n_clusters=3, init='k-means++', random_state= 42)
y_predict= kmeans.fit_predict(x)

mtp.scatter(x[y_predict == 0, 0], x[y_predict == 0, 1], s = 100, c = 'blue', label = 'Cluster 1') #for first cluster
mtp.scatter(x[y_predict == 1, 0], x[y_predict == 1, 1], s = 100, c = 'green', label = 'Cluster 2') #for second cluster
mtp.scatter(x[y_predict== 2, 0], x[y_predict == 2, 1], s = 100, c = 'red', label = 'Cluster 3') #for third cluster
mtp.scatter(kmeans.cluster_centers_[:, 0], kmeans.cluster_centers_[:, 1], s = 300, c = 'yellow', label = 'Centroid')
mtp.title('Customer Segmentation')
mtp.xlabel('Recency')
mtp.ylabel('Income')
mtp.legend()
mtp.show()